### ISSUE TITLE
Ensure cascade deletes work with soft-deletes

### ISSUE THREAD

**Issue by golanglemonade** [datumforge/datum#168]
We recently enabled the soft-delete mixin which uses an ent hook that changes the operation from a delete to an update. 

```
    sd.SetOp(ent.OpUpdate)
```
As part of this change, we need to ensure cascade deletes still work, or update the code to allow these to work.

Example: 
https://github.com/datumforge/datum/blob/main/internal/ent/schema/organization.go#L87-L89

```
edge.To("groups", Group.Type).Annotations(entsql.Annotation{OnDelete: entsql.Cascade}),
edge.To("integrations", Integration.Type).Annotations(entsql.Annotation{OnDelete: entsql.Cascade}),
edge.To("setting", OrganizationSetting.Type).Unique().Annotations(entsql.Annotation{OnDelete: entsql.Cascade}),
```

**Comment by matoszz** [comment]
[PR251](https://github.com/datumforge/datum/pull/251) addresses the bulk of the functionality required, but currently the implemented code path performs an exec and returns an err which will create orphaned records. The remaining functionality which would make this feature complete would be to evaluate the transaction and perform a rollback when encountering an error instead of an exec + error.
