### ISSUE TITLE
Add revision history to database

### ISSUE THREAD

**Issue by matoszz** [datumforge/datum#362]
We should keep track of changes to records in our database with some sort of revision or history construct. Based on experience, we should:
- have the revisions in a separate table (e.g. a _history table, so `users_history` or similar
- revisions on the history table should occur via hooks / interceptors which deal with changes on the underlying table
- history tables should not allow for deletion / modification by the user (should be immutable)
- consideration should be given to long term bloat and only storing the _delta_ column change vs. the entire record
- code to "recover" from a previous revision / modification should exist

Nice to have would be if these history / audit tables lived in a separate database entirely (or you could have the option of creating an audit database along side the main as a deployment option of the stack)

**Comment by golanglemonade** [comment]
Dropping my notes from looking at enthistory:

Fork: https://github.com/datumforge/datum/compare/enthistory-funk?expand=1
* can't use enums, have to switch to GoTypes (pretty easy)
* schemas with SkipAll (verification + reset tokens) have to be excluded
*  something is up with some Nillable fields
* PAT schema is just unhappy (name conflicts because PersonalAccessTokenHistory --> path  and that conflicts with gqlgen so we would need rename the schema)
* doesn't like JSON Fields
* Doesn't like bools (thats the panic: interface conversion: interface {} is nil, not bool error above)
and more...

**Comment by golanglemonade** [comment]
This will be resolved by https://github.com/datumforge/datum/issues/711, closing this one out
